config/routes.rb
Rails.application.routes.draw do

	resources :contact

	resources :workshops do
  		resources :bookings
  	end

	get '/register' => 'users#new'
	post '/users' => 'users#create'

	get '/signin' => 'sessions#new'
	post '/signin' => 'sessions#create'
	delete '/signout' => 'sessions#destroy'

	resources :sessions, only: [:create]
	resources :users, only: [:new, :create, :show, :edit]

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'welcome#index'

	get 'bookings/:id/braintree/new' => "braintree#new", as: 'braintree_new'
	post 'bookings/:id/braintree/checkout' => "braintree#checkout", as: 'braintree_checkout'

	get '/search' => 'workshops#search', as: "search"
end

app/models/workshop.rb
class Workshop < ApplicationRecord
	belongs_to :user
	has_many :bookings, dependent: :destroy
	mount_uploaders :avatar, AvatarUploader

	scope :title, -> (check_workshop_title) { where "title ILIKE?", check_workshop_title }
	scope :price_range, -> (from,to) {where ("price >= ? AND price <= ?"), from, to}

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController

  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  before_action :check_create_rights, only: [:new, :create]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)
    @workshop.user_id = current_user.id

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @workshop = Workshop.all
    # @workshop = Workshop.page(params[:page]).per(4)
    @workshop = @workshop.price_range(params[:from],params[:to]) if params[:from].present? || params[:to].present?
    filtering_params(params).each do |key, value|
    @workshop = @workshop.public_send(key, value) if value.present?
    end

     respond_to do |format|
      format.html
      format.js { render :layout => false }
      format.json { render json: @workshop }
       end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:title, :description, :date, :time, :category, :price, :total, {avatar: []})
    end

    def filtering_params(params)
      params.slice(:title, :description, :date, :time, :category, :price)
    end

    def check_create_rights

    end

end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<div class="container">
  <%= form_with(model: workshop, local: true) do |form| %>
  <% if workshop.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

    <ul>
      <% workshop.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :Date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :Time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :Category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :Total %>
    <%= form.number_field :total %>
  </div>

  <div class="field">
    <%= form.label :Image %>
    <%= form.file_field :avatar, multiple:true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

</div>

app/views/workshops/destroy.js.erb
$('.destroy').bind('ajax:success', function() {
	$(this).closest('tr').fadeOut();

	});

app/views/workshops/edit.html.erb
<h1>Editing Workshop</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Show', @workshop %> |
<%= link_to 'Back', workshops_path %>

app/views/workshops/index.html.erb
<div class="container fluid">
<p id="notice"><%= notice %></p>
<h1>Workshops</h1><hr>

<table>
  <thead>
    <tr class="">
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Time</th>
      <th>Category</th>
      <th>Price</th>
      <th>Total</th>
 <!--      <th>
        <#%if workshop.avatar != nil %>
          <img class="img-fluid" style="width: auto; height: auto;" src= <#%= workshop.avatar[0]%> />
        <#% else %>
          <img class="img-fluid" style="width: auto; height: auto;" src= "https://www.nato-pa.int/sites/default/files/default_images/default-image.jpg"/>
        <#% end %> </th>

      <th colspan="3"></th> -->
    </tr> 
  </thead>

  <tbody>
    <% @workshops.order(:title).each_with_index do |workshop, index| %>

      <tr class=" ">
        <td><%= workshop.title %></td>
        <td><%= workshop.description %></td>
        <td><%= workshop.date %></td>
        <td><%= workshop.time %></td>
        <td><%= workshop.category %></td>
        <td><%= workshop.price %></td>
        <td><%= workshop.total %></td>
        <td>
        <%if workshop.avatar != nil %>
          <img class="img-fluid" style="width: auto; height: auto;" src= <%= workshop.avatar[0]%> />
        <% else %>
          <img class="img-fluid" style="width: auto; height: auto;" src= "https://www.nato-pa.int/sites/default/files/default_images/default-image.jpg"/>
        <% end %>
        </td>
        <td><%= link_to 'Show', workshop %></td>
        <td><%= link_to 'Edit', edit_workshop_path(workshop) %></td>
        <td><%= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "destroy" %></td>
      </tr>

  </tbody>

<% end %>
</table>

<br>

<%= link_to 'New Workshop', new_workshop_path %>

</div>

app/views/workshops/new.html.erb
<div class="container">
<h1>New Workshop</h1><hr>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Back', workshops_path %>
</div>

app/views/workshops/search.html.erb
<div class="container fluid">
<h2>Result</h2>
<% @workshop.order(updated_at: :desc).each do |workshop| %>
<hr>
<p>Title: <%= workshop.title %></p>
<p>Descrp: <%= workshop.description %></p>
<p>Date: <%= workshop.date %></p>
<p>Time: <%= workshop.time %></p>
<p>Category: <%= workshop.category %></p>
<p>Price: <%= workshop.price %></p>

<%= link_to 'Show', workshop_path(workshop) %>

<% end %>
</div>

app/views/workshops/show.html.erb
<div class="container" style="margin-top: 20px">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @workshop.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workshop.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @workshop.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @workshop.time %>
</p>

<p>
  <strong>Category:</strong>
  <%= @workshop.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @workshop.price %>
</p>

<p>
  <strong>Total:</strong>
  <%= @workshop.total %>
</p>

<p>
  <strong>Gallery:</strong>
    <% if @workshop.avatar != nil %>
    <% @workshop.avatar.each do |img| %>
    <%= image_tag img.url, :class => "img-fluid" %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_workshop_path(@workshop) %> |
<%= link_to 'Back', workshops_path %> |
<%= link_to 'Book Slot', new_workshop_booking_path(@workshop, @booking, @current_user) %>

</div>