config/routes.rb
Rails.application.routes.draw do

	resources :contact

	resources :workshops do
  		resources :bookings
  	end

	get '/register' => 'users#new'
	post '/users' => 'users#create'

	get '/signin' => 'sessions#new'
	post '/signin' => 'sessions#create'
	delete '/signout' => 'sessions#destroy'

	resources :sessions, only: [:create]
	resources :users, only: [:new, :create, :show, :edit]

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'welcome#index'

	get 'bookings/:id/braintree/new' => "braintree#new", as: 'braintree_new'
	post 'bookings/:id/braintree/checkout' => "braintree#checkout", as: 'braintree_checkout'

	get '/search' => 'workshops#search', as: "search"
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :email, uniqueness: true, presence: true
	has_many :authentications, dependent: :destroy
	has_many :workshops, dependent: :destroy
	has_many :bookings, dependent: :destroy

	def self.create_with_auth_and_hash(authentication, auth_hash)
	   user = self.create!(
		 first_name: auth_hash["info"]["given_name"],
		 last_name: auth_hash["info"]["family_name"],
	     email: auth_hash["info"]["email"],
	     password: SecureRandom.hex(10)
	   )
		user.authentications << authentication
		return user
	end

 	# grab google to access google for user data
	def google_token
 		x = self.authentications.find_by(provider: 'google_oauth2')
 		return x.token unless x.nil?
 	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, :required => "true", :autocomplete => "off" %>
  </div>

  <div class="text-field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, :required => "true", :autocomplete => "off" %>
  </div>

  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, :required => "true", :autocomplete => "off" %>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password, :required => "true", :autocomplete => "off" %>
  </div>

  <div class="password-field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, :required => "true", :autocomplete => "off" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">
	<h1>New User</h1>

	<%= render 'form', user: @user %>

	<%= link_to "Sign in with Google", "/auth/google_oauth2" %>

	<%= link_to 'Back', root_path %>
</div>

app/views/users/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>First name:</strong>
	  <%= @user.first_name %>
	</p>

	<p>
	  <strong>Last name:</strong>
	  <%= @user.last_name %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @user.email %>
	</p>

	<p>
	  <strong>Password digest:</strong>
	  <%= @user.password_digest %>
	</p>

	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Sign in to continue', signin_path %>
</div>